# Generated by Django 2.2.3 on 2019-07-18 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('towncrierapp', '0005_auto_20190718_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
