# Generated by Django 2.2.3 on 2019-07-18 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('towncrierapp', '0006_message_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('operation', models.CharField(choices=[('ADD_MESSAGE', 'ADD_MESSAGE'), ('PUBLISH_MESSAGE', 'PUBLISH_MESSAGE')], max_length=20)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='towncrierapp.SlackUser')),
            ],
        ),
    ]
