# Generated by Django 2.2.3 on 2019-07-19 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('towncrierapp', '0008_auto_20190719_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='message',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='towncrierapp.Message'),
            preserve_default=False,
        ),
    ]
